#from Exercise2 import Faulty_Calculator
import Exercise2 as Ex2
Ex2.Faulty_Calculator()

